# Generated by Django 4.0.3 on 2022-04-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_remove_exam_start_at_exam_section_exam_starts_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattempt',
            name='mark',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studentattempt',
            name='finished_at',
            field=models.DateTimeField(null=True),
        ),
    ]
