# Generated by Django 4.0.3 on 2022-04-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_studentattempt_mark_alter_studentattempt_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestion',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
