# Generated by Django 4.0.3 on 2022-04-08 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_studentquestion_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPickedChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.choice')),
            ],
            options={
                'db_table': 'student_picked_choice',
            },
        ),
        migrations.CreateModel(
            name='StudentQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.studentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
            ],
            options={
                'db_table': 'student_question_answer',
            },
        ),
        migrations.RemoveField(
            model_name='studentquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentquestion',
            name='student_attempt',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='StudentQuestion',
        ),
        migrations.AddField(
            model_name='studentpickedchoice',
            name='student_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_choices', to='exam.studentquestionanswer'),
        ),
    ]
