# Generated by Django 4.0.2 on 2022-03-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='link',
        ),
        migrations.AddField(
            model_name='lecture',
            name='file',
            field=models.FileField(null=True, upload_to='lecture'),
        ),
    ]
