# Generated by Django 4.0.3 on 2022-03-23 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('department', '0004_alter_lecture_section_alter_section_element'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(null=True)),
                ('file', models.FileField(null=True, upload_to='homeworks/exercices')),
                ('endTime', models.DateTimeField()),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.element')),
            ],
        ),
        migrations.CreateModel(
            name='StudentHomeworkAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(null=True)),
                ('file', models.FileField(null=True, upload_to='homeworks/answers')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
    ]
