# Generated by Django 4.0.3 on 2022-03-23 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('department', '0005_homework_studenthomeworkanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='element',
        ),
        migrations.AddField(
            model_name='homework',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='department.section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studenthomeworkanswer',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='department.homework'),
        ),
        migrations.AlterField(
            model_name='studenthomeworkanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='authentication.student'),
        ),
    ]
