# Generated by Django 4.0.3 on 2022-03-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_remove_homework_element_homework_section_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='endTime',
            new_name='deadline',
        ),
    ]
