# Generated by Django 4.0.3 on 2022-03-25 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('department', '0007_rename_endtime_homework_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomeworkanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_homeworks', to='authentication.student'),
        ),
    ]
