# Generated by Django 4.0.3 on 2022-03-25 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('department', '0009_alter_element_module_alter_module_department'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studying',
            name='student',
        ),
        migrations.AddField(
            model_name='studying',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studying',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studyings', to='authentication.department'),
        ),
    ]
