# Generated by Django 4.0.3 on 2022-03-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_alter_element_module_alter_module_department'),
        ('authentication', '0001_initial'),
        ('student', '0005_lecturefinished_homeworkfinished'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homeworkfinished',
            unique_together={('student', 'homework')},
        ),
        migrations.AlterUniqueTogether(
            name='lecturefinished',
            unique_together={('student', 'lecture')},
        ),
    ]
