# Generated by Django 4.0.3 on 2022-03-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_homeworkfinished_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homeworkfinished',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='lecturefinished',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='elementlog',
            table='element_log',
        ),
        migrations.AlterModelTable(
            name='homeworkfinished',
            table='homework_finished',
        ),
        migrations.AlterModelTable(
            name='lecturefinished',
            table='lecture_finished',
        ),
        migrations.AlterModelTable(
            name='studying',
            table='study_in',
        ),
    ]
